# Generated by Django 3.1.3 on 2020-11-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airman',
            fields=[
                ('airman_id', models.AutoField(primary_key=True, serialize=False)),
                ('fitness_level', models.CharField(choices=[('excellent', 'EXCELLENT'), ('satisfactory', 'SATISFACTORY'), ('pass', 'PASS'), ('unsatisfactory', 'UNSATISFACTORY'), ('fail', 'FAIL'), ('exemption', 'EXEMPTION')], default='satisfactory', max_length=50)),
                ('rank', models.CharField(choices=[('ab', 'AB'), ('amn', 'AMN'), ('a1c', 'A1C'), ('sra', 'SRA'), ('ssgt', 'SSGT'), ('tsgt', 'TSGT'), ('msgt', 'MSGT'), ('smsgt', 'SMSGT'), ('cmsgt', 'CMSGT'), ('2nd lt', '2ND LT'), ('capt', 'CAPT'), ('maj', 'MAJ'), ('lt col', 'LT COL'), ('col', 'COL'), ('brig gen', 'BRIG GEN'), ('maj gen', 'MAJ GEN'), ('lt gen', 'LT GEN'), ('gen', 'GEN')], default='ab', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=50)),
                ('ssn', models.IntegerField()),
                ('airman_slug', models.SlugField(max_length=9, unique_for_date='test_date')),
                ('test_date', models.DateField()),
                ('ptl', models.BooleanField(default=False)),
                ('ufpm', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physical_Training_Leader',
            fields=[
                ('ptl_id', models.AutoField(primary_key=True, serialize=False)),
                ('ptl_certification_date', models.DateField()),
                ('ptl_expiration_date', models.DateField()),
                ('cpr_expiration_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airman')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Fitness_Program_Manager',
            fields=[
                ('ufpm_id', models.AutoField(primary_key=True, serialize=False)),
                ('ufpm_certification_date', models.DateField()),
                ('ufpm_expiration_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airman')),
                ('ptl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.physical_training_leader')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_start_date', models.DateField()),
                ('profile_expiration_date', models.DateField()),
                ('profile_details', models.TextField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airman')),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('failure_id', models.AutoField(primary_key=True, serialize=False)),
                ('failure_date', models.DateField()),
                ('be_well_completion_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airman')),
            ],
        ),
    ]
