# Generated by Django 3.1.3 on 2020-11-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airmen',
            fields=[
                ('airman_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=50)),
                ('ssn', models.IntegerField()),
                ('test_date', models.DateField()),
                ('ptl', models.BooleanField(default=False)),
                ('ufpm', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='fitness_level',
            fields=[
                ('fitness_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('fitness_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='physical_training_leader',
            fields=[
                ('ptl_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_date', models.DateField()),
                ('ptl_expiration_date', models.DateField()),
                ('cpr_expiration_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airmen')),
            ],
        ),
        migrations.CreateModel(
            name='unit_fitness_program_manager',
            fields=[
                ('ufpm_id', models.AutoField(primary_key=True, serialize=False)),
                ('ufpm_certification_date', models.DateField()),
                ('ufpm_expiration_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airmen')),
                ('ptl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.physical_training_leader')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_start_date', models.DateField()),
                ('profile_expiration_date', models.DateField()),
                ('activities_allowed', models.TextField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airmen')),
            ],
        ),
        migrations.CreateModel(
            name='failure',
            fields=[
                ('failure_id', models.AutoField(primary_key=True, serialize=False)),
                ('failure_date', models.DateField()),
                ('be_well_completion_date', models.DateField()),
                ('airman_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.airmen')),
            ],
        ),
        migrations.AddField(
            model_name='airmen',
            name='fitness_level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unit.fitness_level'),
        ),
    ]
