# Generated by Django 3.1.3 on 2020-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='rank',
            field=models.CharField(choices=[('ab', 'AB'), ('amn', 'Amn'), ('a1c', 'A1C'), ('sra', 'SrA'), ('ssgt', 'SSgt'), ('tsgt', 'TSgt'), ('msgt', 'MSgt'), ('smsgt', 'SMSgt'), ('cmsgt', 'CMSgt'), ('2nd lt', '2nd Lt'), ('capt', 'Capt'), ('maj', 'Maj'), ('lt col', 'Lt Col'), ('col', 'Col'), ('brig gen', 'Brig Gen'), ('maj gen', 'Maj Gen'), ('lt gen', 'Lt Gen'), ('gen', 'General')], default='ab', max_length=10),
        ),
    ]
