# Generated by Django 3.1.3 on 2020-11-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_auto_20201122_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='fitness_level',
            field=models.CharField(choices=[('Excellent', 'EXCELLENT'), ('Satisfactory', 'SATISFACTORY'), ('Pass', 'PASS'), ('Unsatisfactory', 'UNSATISFACTORY'), ('Fail', 'FAIL'), ('Exemption', 'EXEMPTION')], default='satisfactory', max_length=50),
        ),
    ]
