# Generated by Django 3.1.3 on 2020-11-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0006_auto_20201122_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airman',
            name='active',
        ),
        migrations.AddField(
            model_name='airman',
            name='active_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
    ]
