# Generated by Django 3.1.3 on 2020-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0007_auto_20201122_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airman',
            name='airman_slug',
            field=models.SlugField(unique_for_date='test_date'),
        ),
    ]
