# Generated by Django 3.1.3 on 2020-11-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_auto_20201122_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airman',
            options={'ordering': ('last_name',)},
        ),
    ]
