# Generated by Django 3.1.3 on 2020-11-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0009_auto_20201122_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('profile_expiration_date',)},
        ),
    ]
