# Generated by Django 3.1.3 on 2020-11-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0010_auto_20201122_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physical_training_leader',
            options={'ordering': ('ptl_expiration_date',)},
        ),
        migrations.AlterModelOptions(
            name='unit_fitness_program_manager',
            options={'ordering': ('ufpm_expiration_date',)},
        ),
    ]
